<#!
.SYNOPSIS
    Launches the most recent Paranoid Antivirus Suite installer generated by CPack.
.DESCRIPTION
    Searches the build artifacts for the newest NSIS installer, launches it with optional silent
    flags, and waits for completion while surfacing any errors.
.PARAMETER InstallerPath
    Optional explicit path to the installer .exe. If omitted the script searches under build/.
.PARAMETER Silent
    Runs the NSIS installer in unattended mode.
.PARAMETER SkipLaunch
    Suppresses automatic GUI launch after installation completes.
#>
[CmdletBinding()]
param(
    [string]$InstallerPath,
    [switch]$Silent,
    [switch]$SkipLaunch
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

function Get-ParanoidInstallPath {
    $roots = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
    )
    foreach ($root in $roots) {
        if (-not (Test-Path $root)) { continue }
        foreach ($key in Get-ChildItem $root) {
            try {
                $displayName = $key.GetValue("DisplayName")
                if ($displayName -and ($displayName -eq "Paranoid Antivirus Suite")) {
                    $installLocation = $key.GetValue("InstallLocation")
                    if ($installLocation -and (Test-Path $installLocation)) {
                        return $installLocation
                    }
                    $uninstallString = $key.GetValue("UninstallString")
                    if ($uninstallString) {
                        $expanded = [Environment]::ExpandEnvironmentVariables($uninstallString).Trim('"')
                        $candidate = Split-Path $expanded -Parent
                        if ($candidate -and (Test-Path $candidate)) {
                            return $candidate
                        }
                    }
                }
            }
            catch {
                continue
            }
        }
    }
    return $null
}

function Invoke-ParanoidGuiLaunch {
    param([string]$InstallRoot)

    $launcher = Join-Path (Join-Path $InstallRoot "bin") "paranoid_gui.cmd"
    if (-not (Test-Path $launcher)) {
        Write-Warning "Paranoid GUI launcher not found at '$launcher'."
        return
    }

    Write-Host "Launching Paranoid Antivirus GUI..." -ForegroundColor Cyan
    Start-Process -FilePath $launcher | Out-Null
}

if (-not $InstallerPath) {
    $candidates = Get-ChildItem -Path (Join-Path $repoRoot "build") -Filter "*ParanoidAntivirusSuite*.exe" -Recurse -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending
    if (-not $candidates) {
        throw "No installer executables found. Run scripts/build_windows.ps1 -Package first."
    }
    $InstallerPath = $candidates[0].FullName
}

if (-not (Test-Path $InstallerPath)) {
    throw "Installer '$InstallerPath' not found."
}

Write-Host "Running installer: $InstallerPath" -ForegroundColor Cyan
$arguments = @()
if ($Silent) {
    $arguments += "/S"
}

$process = Start-Process -FilePath $InstallerPath -ArgumentList $arguments -PassThru -Wait
if ($process.ExitCode -ne 0) {
    throw "Installer exited with code $($process.ExitCode)."
}

Write-Host "Installation completed." -ForegroundColor Green
if (-not $SkipLaunch) {
    $installRoot = Get-ParanoidInstallPath
    if ($installRoot) {
        Invoke-ParanoidGuiLaunch -InstallRoot $installRoot
    }
    else {
        Write-Warning "Unable to determine installation directory. GUI launch skipped."
    }
}
