<#!
.SYNOPSIS
    Launches the most recent Paranoid Antivirus Suite installer generated by CPack.
.DESCRIPTION
    Searches the build artifacts for the newest NSIS installer, launches it with optional silent
    flags, and waits for completion while surfacing any errors.
.PARAMETER InstallerPath
    Optional explicit path to the installer .exe. If omitted the script searches under build/.
.PARAMETER Silent
    Runs the NSIS installer in unattended mode.
#>
[CmdletBinding()]
param(
    [string]$InstallerPath,
    [switch]$Silent
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

if (-not $InstallerPath) {
    $candidates = Get-ChildItem -Path (Join-Path $repoRoot "build") -Filter "*ParanoidAntivirusSuite*.exe" -Recurse -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending
    if (-not $candidates) {
        throw "No installer executables found. Run scripts/build_windows.ps1 -Package first."
    }
    $InstallerPath = $candidates[0].FullName
}

if (-not (Test-Path $InstallerPath)) {
    throw "Installer '$InstallerPath' not found."
}

Write-Host "Running installer: $InstallerPath" -ForegroundColor Cyan
$arguments = @()
if ($Silent) {
    $arguments += "/S"
}

$process = Start-Process -FilePath $InstallerPath -ArgumentList $arguments -PassThru -Wait
if ($process.ExitCode -ne 0) {
    throw "Installer exited with code $($process.ExitCode)."
}

Write-Host "Installation completed." -ForegroundColor Green
